### ISSUE TITLE
Stop Memmon while installing upgrades

### ISSUE THREAD

**Issue by jone** [4teamwork/ftw-buildouts#60]
Having Memmon running while executing upgrade steps can result in an unexpected restart of the instance, in which case the upgrade is aborted.

```python
Traceback (most recent call last):
  File "bin/upgrade", line 252, in <module>
    sys.exit(ftw.upgrade.command.main())
  File "/home/zope/eggs/ftw.upgrade-2.0.5-py2.7.egg/ftw/upgrade/command/__init__.py", line 197, in main
    UpgradeCommand()()
  File "/home/zope/eggs/ftw.upgrade-2.0.5-py2.7.egg/ftw/upgrade/command/__init__.py", line 170, in __call__
    args.func(args)
  File "/home/zope/eggs/ftw.upgrade-2.0.5-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 122, in func_wrapper
    return func(args, requestor)
  File "/home/zope/eggs/ftw.upgrade-2.0.5-py2.7.egg/ftw/upgrade/command/jsonapi.py", line 131, in func_wrapper
    return func(*args, **kwargs)
  File "/home/zope/eggs/ftw.upgrade-2.0.5-py2.7.egg/ftw/upgrade/command/install.py", line 105, in install_command
    for line in response.iter_lines(chunk_size=30):
  File "/home/zope/eggs/requests-2.11.1-py2.7.egg/requests/models.py", line 720, in iter_lines
    for chunk in self.iter_content(chunk_size=chunk_size, decode_unicode=decode_unicode):
  File "/home/zope/eggs/requests-2.11.1-py2.7.egg/requests/models.py", line 679, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

--

In order to avoid such problems we should always shut down Memmon while executing upgrade steps.

**Comment by jone** [comment]
Duplicate of https://github.com/4teamwork/plone-git-deployment/issues/8 🙈
